### ISSUE TITLE
Sviluppo di un modulo per autenticazione SPID su Drupal

### ISSUE THREAD

**Issue by alranel** [italia/spid-drupal-module#1]
Lo scopo di un plugin SPID per Drupal dovrebbe essere quello di:

* visualizzare il [bottone di login](https://github.com/italia/spid-sp-access-button) nella pagina di autenticazione
* creare automaticamente l'utente dopo che l'autenticazione SPID è avvenuta

Una soluzione facile è quella di usare SimpleSAMLphp, che è già disponibile [preconfigurato per SPID](https://github.com/italia/spid-sp-simplesamlphp).

In alternativa si potrebbe basare l'implementazione su https://www.drupal.org/project/samlauth

[Nota: [Porte Aperte sul Web](http://www.porteapertesulweb.it/) ha annunciato di avere sviluppato un plugin SPID-Joomla, ma ad oggi i sorgenti non sono stati rilasciati e non sono noti i dettagli dell'implementazione.]

**Comment by robertoperuzzo** [comment]
Ciao Alex,
do volentieri il mio supporto per sviluppare il modulo Drupal. Hai già una roadmap da seguire?

**Comment by lussoluca** [comment]
Ciao Alex e ciao Roberto,
noi stiamo lavorando già da un po' alla versione per Drupal 8 che dovrebbe essere pronta a breve (basata su https://www.drupal.org/project/samlauth). Entro la fine di questa settimana facciamo un PR con il primo draft se per voi va bene.

Poi ogni contributo è benvenuto :-)

@alexrj potresti per favore sostituire Joomla con Drupal nel messaggio qua sopra :-)

**Comment by robertoperuzzo** [comment]
Ottimo Luca.

**Comment by ruphy** [comment]
Coretto io :-)
se volete sincronizzarvi ricordate di usare pure lo slack, è aperto! (canale #spid-drupal-module, slack.developers.italia.it)

**Comment by lussoluca** [comment]
Ciao abbiamo caricato la prima versione qua https://www.drupal.org/project/spid ogni commento e miglioria sono benvenuti!

**Comment by lussoluca** [comment]
@alexrj PR qua: https://github.com/italia/spid-drupal-module/pull/2
